### ISSUE TITLE
[BUG] Unable to load tokenizer of T5

### ISSUE THREAD

**Issue by zcbenz** [lenML/tokenizers#7]
```js
import {AutoTokenizer} from '@huggingface/transformers'
import {TokenizerLoader} from '@lenml/tokenizers'

let tokenizer = await AutoTokenizer.from_pretrained('google-t5/t5-small')
console.log(tokenizer.encode('test'))

tokenizer = await TokenizerLoader.fromPreTrainedUrls({
  tokenizerJSON: 'https://huggingface.co/google-t5/t5-small/resolve/main/tokenizer.json',
  tokenizerConfig: 'https://huggingface.co/google-t5/t5-small/resolve/main/tokenizer_config.json'
})
console.log(tokenizer.encode('test'))
```

Throws error:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at Function.populateNodes (file:///private/tmp/test-tok/node_modules/@lenml/tokenizers/dist/main.mjs:3:32526)
    at Function.tokenize (file:///private/tmp/test-tok/node_modules/@lenml/tokenizers/dist/main.mjs:3:32856)
    at Function.encode (file:///private/tmp/test-tok/node_modules/@lenml/tokenizers/dist/main.mjs:3:32930)
    at Function._call (file:///private/tmp/test-tok/node_modules/@lenml/tokenizers/dist/main.mjs:3:30694)
    at Function.closure [as model] (file:///private/tmp/test-tok/node_modules/@lenml/tokenizers/dist/main.mjs:1:20856)
    at file:///private/tmp/test-tok/node_modules/@lenml/tokenizers/dist/main.mjs:4:16122
    at Array.map (<anonymous>)
    at Function._encode_text (file:///private/tmp/test-tok/node_modules/@lenml/tokenizers/dist/main.mjs:4:15780)
    at Function._tokenize_helper (file:///private/tmp/test-tok/node_modules/@lenml/tokenizers/dist/main.mjs:4:16552)
    at Function._encode_plus (file:///private/tmp/test-tok/node_modules/@lenml/tokenizers/dist/main.mjs:4:16268)
```

**Comment by zhzLuke96** [comment]
thx feedback

You are correct. The issue has been resolved in the latest code of `transformers`. It was fixed in this [commit 
8c22943](https://github.com/lenML/tokenizers/commit/8c229433c1f93516e6f76dc9a10f1df1c976fcfc).  
We’ve also added a test case for this tokenizer under `packages/tests`. If you encounter any further issues, you can refer to the code in [`packages/tests/tests/tokenizers.test.ts`](https://github.com/lenML/tokenizers/blob/main/packages/tests/tests/tokenizers.test.ts). Contributions with additional test cases are also welcome.

The new version, [@lenml/tokenizers@3.0.3](https://www.npmjs.com/package/@lenml/tokenizers/v/3.0.3), has been released.
